
export const ErrorCodes = {
    ERR_CPF_INVALIDO:               100,
    ERR_CPF_DUPLICADO:              101,
    ERR_NOME_INVALIDO:              102,
    ERR_DATA_PACIENTE_INVALIDA:     103,
    ERR_IDADE_INSUFICIENTE:         104,
    ERR_PACIENTE_NAO_CADASTRADO:    105,
    ERR_PACIENTE_AGENDADO:          106,
    ERR_PACIENTE_INCOMPLETO:        107,
    
    ERR_DATA_CONSULTA_INVALIDA:     200,
    ERR_DATA_CONSULTA_ANTERIOR:     201,
    ERR_DATA_CONSULTA_HOJE_FECHADO: 202,
    ERR_HORA_INVALIDA:              203,
    ERR_HORA_HORARIO_INVALIDO:      204,
    ERR_HORA_FINAL_ANTES_INICIAL:   205,
    ERR_HORA_PASSADA:               206,
    ERR_HORA_HORARIO_FECHADO:       207,
    ERR_HORA_SEM_DATA_CONSULTA:     208,
    ERR_HORA_SEM_HORA_INICIAL:      209,
    ERR_CONSULTA_INCOMPLETA:        210,
    ERR_CONSULTA_NAO_ENCONTRADA:    211,

    ERR_DATA_FINAL_MENOR_INICIAL:   300,
    ERR_ENTRADA_INVALIDA_AGENDA:    301
};